---
- name: Install Oh My Zsh
  ansible.builtin.shell: |
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
    depth: 1
    version: master

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
    depth: 1
    version: master

- name: Symlink .zshrc
  ansible.builtin.file:
    src: "{{ dotfiles_dir }}/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: link
    force: true

- name: Set zsh as default shell
  when: is_linux
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
